Repository francep2p/p2p.paris, pull requests merged in 2019-11, with the labels that each got.

#49 chore: add https://github.com/francep2p/community/issues/47 talk
  content/event/monthly-3/index.fr.md
  content/event/monthly-3/index.md
Labels: 🔍 Ready for Review

#50 WIP feat: paris p2p festival #0
  content/event/festival-0/index.fr.md
  content/event/festival-0/index.md
  content/event/festival-0/paris_p2p_festival_0.png
  themes/p2pparis/layouts/event/single.html
Labels: 🚧 WIP

#52 chore: post-event bump
  content/event/monthly-3/index.fr.md
  content/event/monthly-3/index.md
  content/event/monthly-4/index.fr.md
  content/event/monthly-4/index.md
Labels: 🔍 Ready for Review

#55 Upgrade Hugo & sort event block
  netlify.toml
  themes/p2pparis/layouts/_default/index.html
Labels: 🔍 Ready for Review

#56 feat: add 404 page layout
  config.yml
  themes/p2pparis/layouts/404.html
  themes/p2pparis/layouts/partials/header.html
  themes/p2pparis/static/css/creative.css
  themes/p2pparis/static/img/metro_paris.jpg
Labels: 🔍 Ready for Review

#57 feat: add lottie animation on homepage
  themes/p2pparis/layouts/_default/index.html
  themes/p2pparis/layouts/partials/footer.html
  themes/p2pparis/static/css/creative.css
  themes/p2pparis/static/js/lottie.js
Labels: 🔍 Ready for Review

#58 Add 404 redirect
  themes/p2pparis/static/_redirects
Labels: ✅ Approved

#59 chore: embed festival's hackmd intro
  content/event/festival-0/index.fr.md
  content/event/festival-0/index.md
Labels: 🔍 Ready for Review

#61 Automate event status
  content/event/festival-0/index.fr.md
  content/event/festival-0/index.md
  content/event/monthly-0/index.fr.md
  content/event/monthly-0/index.md
  content/event/monthly-1/index.fr.md
  content/event/monthly-1/index.md
  content/event/monthly-2/index.fr.md
  content/event/monthly-2/index.md
  content/event/monthly-3/index.fr.md
  content/event/monthly-3/index.md
  content/event/monthly-4/index.fr.md
  content/event/monthly-4/index.md
  content/event/monthly-5/index.fr.md
  content/event/monthly-5/index.md
  content/event/monthly-6/index.fr.md
  content/event/monthly-6/index.md
  content/event/monthly-7/index.fr.md
  content/event/monthly-7/index.md
  content/event/monthly-8/index.fr.md
  content/event/monthly-8/index.md
  content/event/monthly-9/index.fr.md
  content/event/monthly-9/index.md
  themes/p2pparis/layouts/_default/baseof.html
  themes/p2pparis/layouts/_default/index.html
  themes/p2pparis/layouts/_default/single.html
  themes/p2pparis/layouts/event/list.html
  themes/p2pparis/layouts/event/single.html
  themes/p2pparis/layouts/partials/block_event.html
  themes/p2pparis/static/css/creative.css
Labels: 🔍 Ready for Review

#63 chore: hide montly 5
  content/event/monthly-5/index.fr.md
  content/event/monthly-5/index.md
Labels: 🔍 Ready for Review

#64 Automate daily build
  .github/workflows/daily-build.yml
Labels: 🔍 Ready for Review

#65 Improve events display
  config.yml
  content/event/festival-0/index.fr.md
  content/event/festival-0/index.md
  themes/p2pparis/layouts/_default/index.html
  themes/p2pparis/layouts/event/single.html
  themes/p2pparis/layouts/partials/content_event.html
  themes/p2pparis/layouts/partials/event_about.html
  themes/p2pparis/layouts/partials/event_info.html
  themes/p2pparis/layouts/partials/header.html
  themes/p2pparis/layouts/partials/navbar.html
  themes/p2pparis/layouts/partials/section_links.html
  themes/p2pparis/static/css/creative.css
  themes/p2pparis/static/img/bg_light.png
  themes/p2pparis/static/img/bg_metro.jpg
  themes/p2pparis/static/img/paris_p2p_small.svg
  themes/p2pparis/static/js/creative.js
Labels: ✅ Approved

#67 Add values and translate content
  config.yml
  content/_index.fr.md
  content/_index.md
  content/event/monthly-4/index.fr.md
  content/event/monthly-4/index.md
  content/event/monthly-5/index.fr.md
  content/event/monthly-5/index.md
  content/event/monthly-6/index.fr.md
  content/event/monthly-6/index.md
  content/event/monthly-7/index.fr.md
  content/event/monthly-7/index.md
  content/event/monthly-8/index.fr.md
  content/event/monthly-8/index.md
  content/event/monthly-9/index.fr.md
  content/event/monthly-9/index.md
  content/values/index.fr.md
  content/values/index.md
  i18n/en.yaml
  i18n/fr.yaml
  themes/p2pparis/layouts/_default/index.html
  themes/p2pparis/layouts/_default/single.html
  themes/p2pparis/layouts/partials/event_about.html
  themes/p2pparis/layouts/partials/event_info.html
  themes/p2pparis/layouts/partials/navbar.html
  themes/p2pparis/layouts/partials/section_links.html
  themes/p2pparis/layouts/partials/section_values.html
  themes/p2pparis/layouts/shortcodes/available_slot.html
  themes/p2pparis/static/css/creative.css
Labels: 🔍 Ready for Review

#68 [WIP] Improve events display
  content/_index.fr.md
  content/_index.md
  content/values/index.fr.md
  content/values/index.md
  i18n/en.yaml
  i18n/fr.yaml
  themes/p2pparis/layouts/_default/single.html
  themes/p2pparis/layouts/partials/block_event.html
  themes/p2pparis/static/css/creative.css
Labels: 🚧 WIP

#69 Event status fix
  themes/p2pparis/layouts/_default/baseof.html
  themes/p2pparis/layouts/_default/index.html
  themes/p2pparis/layouts/event/list.html
  themes/p2pparis/layouts/partials/block_event.html
Labels: ✅ Approved

#70 Event status fix
  themes/p2pparis/layouts/_default/baseof.html
  themes/p2pparis/layouts/_default/index.html
  themes/p2pparis/layouts/event/list.html
  themes/p2pparis/layouts/partials/block_event.html
Labels: ✅ Approved

#71 improve responsive
  i18n/en.yaml
  i18n/fr.yaml
  themes/p2pparis/layouts/_default/index.html
  themes/p2pparis/layouts/shortcodes/available_slot.html
  themes/p2pparis/static/css/creative.css
Labels: 🔍 Ready for Review

#72 Add load more events button
  i18n/en.yaml
  i18n/fr.yaml
  themes/p2pparis/assets/js/main.js
  themes/p2pparis/layouts/_default/index.html
  themes/p2pparis/layouts/partials/footer.html
Labels: 🔍 Ready for Review

#74 Format & translate dates
  config.yml
  themes/p2pparis/layouts/partials/block_event.html
  themes/p2pparis/layouts/partials/date.html
  themes/p2pparis/layouts/partials/event_info.html
Labels: ✅ Approved

#77 Add related events
  themes/p2pparis/layouts/event/single.html
  themes/p2pparis/layouts/partials/related_events.html
Labels: ✅ Approved

#78 Add lottie fallback
  themes/p2pparis/layouts/_default/index.html
  themes/p2pparis/static/css/creative.css
  themes/p2pparis/static/js/lottie.js
Labels: 🚧 WIP

#79 feat: update homepage logo to match animation and add event on id on …
  content/event/festival-0/index.fr.md
  content/event/festival-0/index.md
  content/event/monthly-0/index.fr.md
  content/event/monthly-0/index.md
  content/event/monthly-1/index.fr.md
  content/event/monthly-1/index.md
  content/event/monthly-2/index.fr.md
  content/event/monthly-2/index.md
  content/event/monthly-3/index.fr.md
  content/event/monthly-3/index.md
  content/event/monthly-4/index.fr.md
  content/event/monthly-4/index.md
  content/event/monthly-5/index.fr.md
  content/event/monthly-5/index.md
  content/event/monthly-6/index.fr.md
  content/event/monthly-6/index.md
  content/event/monthly-7/index.fr.md
  content/event/monthly-7/index.md
  content/event/monthly-8/index.fr.md
  content/event/monthly-8/index.md
  content/event/monthly-9/index.fr.md
  content/event/monthly-9/index.md
  themes/p2pparis/layouts/event/single.html
  themes/p2pparis/static/css/creative.css
  themes/p2pparis/static/img/paris_p2p.svg
Labels: 🔍 Ready for Review

#75 Add language redirects
  _redirects
  themes/p2pparis/layouts/partials/header.html
  themes/p2pparis/layouts/partials/navbar.html
  themes/p2pparis/static/_redirects
Labels: ✅ Approved
