Repository francep2p/p2p.paris, pull requests merged in 2019-12, with the labels that each got.

#80 fix show today's event as "next"
  themes/p2pparis/layouts/_default/baseof.html
Labels: ✅ Approved

#82 feat: move events section at the top of the page
  config.yml
  themes/p2pparis/layouts/_default/index.html
Labels: ✅ Approved

#84 Fix event spacing and indentation
  content/fest/day-1/index.fr.md
Labels: ✅ Approved

#85 Generate festival events
  config.yml
  content/event/festival-0/index.fr.md
  content/event/festival-0/index.md
  content/fest/_index.fr.md
  content/fest/_index.md
  content/fest/day-1/index.fr.md
  content/fest/day-1/index.md
  content/fest/day-2/index.fr.md
  content/fest/day-2/index.md
  content/fest/day-3/index.fr.md
  content/fest/day-3/index.md
  content/fest/day-4/index.fr.md
  content/fest/day-4/index.md
  content/fest/day-5/index.fr.md
  content/fest/day-5/index.md
  data/festival/en.json
  data/festival/fr.json
  netlify.toml
  pre-build.sh
  scripts/fest_schedule.csv
  scripts/generate-fest.js
  themes/p2pparis/layouts/event/festival.html
  themes/p2pparis/layouts/festival/single.html
  themes/p2pparis/layouts/partials/s_item.html
  themes/p2pparis/layouts/partials/section_schedule.html
Labels: 🔍 Ready for Review

#83 Festival one-page-website
  config.yml
  content/event/festival-0/index.fr.md
  content/event/festival-0/index.md
  data/festival/en.json
  data/festival/fr.json
  i18n/en.yaml
  i18n/fr.yaml
  netlify.toml
  package.json
  pre-build.sh
  scripts/fest_schedule.csv
  scripts/generate-fest.js
  themes/p2pparis/layouts/_default/baseof.html
  themes/p2pparis/layouts/event/festival.html
  themes/p2pparis/layouts/event/single.html
  themes/p2pparis/layouts/partials/day.html
  themes/p2pparis/layouts/partials/footer_festival.html
  themes/p2pparis/layouts/partials/header.html
  themes/p2pparis/layouts/partials/masthead_festival.html
  themes/p2pparis/layouts/partials/navbar_festival.html
  themes/p2pparis/layouts/partials/s_item.html
  themes/p2pparis/layouts/partials/section_about.html
  themes/p2pparis/layouts/partials/section_goals.html
  themes/p2pparis/layouts/partials/section_info.html
  themes/p2pparis/layouts/partials/section_links.html
  themes/p2pparis/layouts/partials/section_numbers.html
  themes/p2pparis/layouts/partials/section_plan.html
  themes/p2pparis/layouts/partials/section_schedule.html
  themes/p2pparis/static/css/creative.css
  themes/p2pparis/static/img/bg_festival.png
  themes/p2pparis/static/img/bg_people.jpg
  themes/p2pparis/static/img/paris_p2p_festival.svg
  themes/p2pparis/static/js/creative.js
Labels: 🔍 Ready for Review

#86 Format short date for festival
  config.yml
  themes/p2pparis/layouts/partials/section_schedule.html
Labels: 🔍 Ready for Review

#88 Dev/alex/festival improvements
  config.yml
  content/_index.fr.md
  data/festival/fr.json
  themes/p2pparis/layouts/_default/index.html
  themes/p2pparis/layouts/partials/masthead_festival.html
  themes/p2pparis/layouts/partials/navbar_festival.html
  themes/p2pparis/layouts/partials/s_item.html
  themes/p2pparis/layouts/partials/section_info.html
  themes/p2pparis/layouts/partials/section_schedule.html
  themes/p2pparis/static/css/creative.css
Labels: 🔍 Ready for Review

#89 Fix typo
  scripts/fest_schedule.csv
Labels: 🔍 Ready for Review

#90 festival english version
  content/event/festival-0/index.fr.md
  content/event/festival-0/index.md
  data/festival/en.json
  data/festival/fr.json
  scripts/fest_schedule.csv
  scripts/fest_schedule_old.csv
  themes/p2pparis/layouts/partials/navbar_festival.html
  themes/p2pparis/layouts/partials/section_about.html
  themes/p2pparis/layouts/partials/section_info.html
  themes/p2pparis/layouts/partials/section_links.html
  themes/p2pparis/static/css/creative.css
Labels: 🔍 Ready for Review

#91 feat: update schedule
  data/festival/en.json
  data/festival/fr.json
  scripts/fest_schedule.csv
  scripts/fest_schedule_old.csv
Labels: 🔍 Ready for Review

#92 Fetch CSV directly
  data/festival/en.json
  data/festival/fr.json
  package.json
  pre-build.sh
  scripts/fest_schedule.csv
  scripts/fest_schedule_old.csv
  scripts/generate-fest.js
Labels: 🔍 Ready for Review

#93 Dev/alex/plan
  themes/p2pparis/layouts/event/festival.html
  themes/p2pparis/layouts/partials/navbar_festival.html
  themes/p2pparis/layouts/partials/section_numbers.html
  themes/p2pparis/layouts/partials/section_plan.html
  themes/p2pparis/static/css/creative.css
  themes/p2pparis/static/img/ground_control_floor_plan.svg
Labels: 🔍 Ready for Review

#94 feat: add images for movies
  data/festival/en.json
  data/festival/fr.json
  scripts/data.csv
  themes/p2pparis/layouts/partials/s_item.html
  themes/p2pparis/static/css/creative.css
  themes/p2pparis/static/img/festival/movie_internets_own_boy.png
  themes/p2pparis/static/img/festival/movie_nothing_to_hide.png
  themes/p2pparis/static/img/festival/movie_protocole.png
Labels: 🔍 Ready for Review

#95 feat: add section speakers and import script from spreashsheet
  content/event/festival-0/index.fr.md
  content/event/festival-0/index.md
  data/festival/speakers.json
  pre-build.sh
  scripts/generate-speakers.js
  themes/p2pparis/layouts/event/festival.html
  themes/p2pparis/layouts/partials/block_speaker.html
  themes/p2pparis/layouts/partials/navbar_festival.html
  themes/p2pparis/layouts/partials/section_about.html
  themes/p2pparis/layouts/partials/section_info.html
  themes/p2pparis/layouts/partials/section_plan.html
  themes/p2pparis/layouts/partials/section_speakers.html
  themes/p2pparis/static/css/creative.css
Labels: ✅ Approved

#96 feat: add some peakers pictures
  data/festival/speakers.json
  themes/p2pparis/static/css/creative.css
  themes/p2pparis/static/img/festival/picture_liliana_carillo.png
  themes/p2pparis/static/img/festival/picture_manel_ruiz.jpg
Labels: 🔍 Ready for Review

#97 feat: add plan legend
  content/event/festival-0/index.fr.md
  content/event/festival-0/index.md
  data/festival/en.json
  data/festival/fr.json
  data/festival/speakers.json
  themes/p2pparis/layouts/partials/section_plan.html
  themes/p2pparis/static/css/creative.css
  themes/p2pparis/static/img/festival/picture_cedric_ringenbach.jpg
Labels: 🔍 Ready for Review

#98 various event improvements
  .gitignore
  config.yml
  content/event/festival-0/index.fr.md
  content/event/festival-0/index.md
  data/festival/en.json
  data/festival/fr.json
  data/festival/speakers.json
  pre-build.sh
  scripts/data.csv
  scripts/generate-fest.js
  scripts/generate-speakers.js
  scripts/gsheetstojson.js
  themes/p2pparis/layouts/partials/header.html
  themes/p2pparis/layouts/partials/s_item.html
  themes/p2pparis/layouts/partials/section_schedule.html
  themes/p2pparis/layouts/partials/section_speakers.html
Labels: ✅ Approved

#99 Festival bonus
  content/event/festival-0/index.fr.md
  themes/p2pparis/layouts/event/festival.html
  themes/p2pparis/layouts/partials/block_speaker.html
  themes/p2pparis/layouts/partials/navbar_festival.html
  themes/p2pparis/layouts/partials/section_info.html
  themes/p2pparis/layouts/partials/section_speakers.html
  themes/p2pparis/static/css/creative.css
  themes/p2pparis/static/js/creative.js
Labels: 🔍 Ready for Review

#100 Dev/alex/tags
  themes/p2pparis/layouts/partials/block_speaker.html
  themes/p2pparis/layouts/partials/s_item.html
  themes/p2pparis/static/css/creative.css
  themes/p2pparis/static/img/festival/picture_adrien_berthou.png
  themes/p2pparis/static/img/festival/picture_alex_masmej.png
  themes/p2pparis/static/img/festival/picture_louis_giraux.jpg
  themes/p2pparis/static/img/festival/picture_pierre_boc.jpg
  themes/p2pparis/static/img/festival/picture_pierre_noizat.png
  themes/p2pparis/static/img/festival/picture_virgile_deville.jpg
  themes/p2pparis/static/js/creative.js
Labels: 🔍 Ready for Review

#101 feat: add speaker pictures and update number
  themes/p2pparis/layouts/partials/section_numbers.html
  themes/p2pparis/static/img/festival/picture_boris_seguy.jpg
  themes/p2pparis/static/img/festival/picture_kris_decoodt.png
Labels: 🔍 Ready for Review

#102 Prepend speaker links with https
  Makefile
  themes/p2pparis/layouts/partials/block_speaker.html
Labels: ✅ Approved

#103 feat: add speakers pictures
  themes/p2pparis/static/img/festival/picture_clement_lesaege.png
  themes/p2pparis/static/img/festival/picture_remi_crussiere.png
Labels: 🔍 Ready for Review

#104 Dev/alex/festival fixes
  themes/p2pparis/layouts/partials/s_item.html
  themes/p2pparis/static/css/creative.css
  themes/p2pparis/static/img/festival/picture_rand_hindi.png
Labels: 🔍 Ready for Review

#105 feat: add missing speakers pictures
  themes/p2pparis/static/css/creative.css
  themes/p2pparis/static/img/festival/picture_alice.png
  themes/p2pparis/static/img/festival/picture_brian_ohagan.png
  themes/p2pparis/static/img/festival/picture_daniele_bourcier.png
  themes/p2pparis/static/img/festival/picture_philippe_m.jpg
Labels: 🔍 Ready for Review

#106 feat: add missing picture
  themes/p2pparis/static/img/festival/picture_primavera_de_filippi.jpg
Labels: 🔍 Ready for Review

#107 feat: match desc links colors with event kind color
  themes/p2pparis/static/css/creative.css
Labels: 🔍 Ready for Review

#109 WIP Generate airtable pages
  .gitignore
  content/event/festival-0/index.fr.md
  content/event/festival-0/index.md
  content/event/monthly-0/index.fr.md
  content/event/monthly-0/index.md
  content/event/monthly-1/index.fr.md
  content/event/monthly-1/index.md
  content/event/monthly-2/index.fr.md
  content/event/monthly-2/index.md
  content/event/monthly-3/index.fr.md
  content/event/monthly-3/index.md
  content/event/monthly-4/index.fr.md
  content/event/monthly-4/index.md
  content/event/monthly-5/index.fr.md
  content/event/monthly-5/index.md
  content/event/monthly-6/index.fr.md
  content/event/monthly-6/index.md
  content/event/monthly-7/index.fr.md
  content/event/monthly-7/index.md
  content/event/monthly-8/index.fr.md
  content/event/monthly-8/index.md
  content/event/monthly-9/index.fr.md
  content/event/monthly-9/index.md
  pre-build.sh
  scripts/generate-airtable-pages.js
  themes/p2pparis/layouts/_default/baseof.html
  themes/p2pparis/layouts/event/list.html
  themes/p2pparis/layouts/event/single.html
  themes/p2pparis/layouts/partials/block_event.html
  themes/p2pparis/layouts/partials/event_info.html
  themes/p2pparis/layouts/partials/related_events.html
  themes/p2pparis/layouts/speakers/list.html
  themes/p2pparis/layouts/speakers/single.html
  themes/p2pparis/layouts/talks/list.html
  themes/p2pparis/layouts/talks/single.html
Labels: 🚧 WIP

#110 Filter paris chapters only & use slug & add logging
  scripts/generate-airtable-pages.js
Labels: ✅ Approved

#111 Add speaker images & add festival
  .gitignore
  pre-build.sh
  scripts/generate-airtable-pages.js
  themes/p2pparis/layouts/partials/block_speaker.html
  themes/p2pparis/layouts/partials/s_item.html
  themes/p2pparis/layouts/partials/section_numbers.html
  themes/p2pparis/layouts/partials/section_schedule.html
  themes/p2pparis/layouts/speakers/list.html
  themes/p2pparis/layouts/speakers/single.html
Labels: ✅ Approved

#115 fix: use proper speaker headline + change title order
  themes/p2pparis/layouts/partials/block_speaker.html
  themes/p2pparis/layouts/partials/header.html
Labels: 🔍 Ready for Review

#116 Add more speaker & talk info
  scripts/generate-airtable-pages.js
  themes/p2pparis/layouts/partials/section_speakers.html
  themes/p2pparis/layouts/speakers/list.html
  themes/p2pparis/layouts/speakers/single.html
  themes/p2pparis/layouts/talks/list.html
  themes/p2pparis/layouts/talks/single.html
Labels: ✅ Approved

#120 fix multi language titles & improve images
  config.yml
  scripts/generate-airtable-pages.js
  themes/p2pparis/assets/css/creative.css
  themes/p2pparis/assets/img/bg_festival.png
  themes/p2pparis/layouts/partials/block_speaker.html
  themes/p2pparis/layouts/partials/header.html
  themes/p2pparis/layouts/partials/s_item.html
Labels: 🔍 Ready for Review
