Repository francep2p/p2p.paris, pull requests merged in 2020-01, with the labels that each got.

#119 feat: translate speakers listing page title
  content/speakers/_index.fr.md
  content/speakers/_index.md
  themes/p2pparis/layouts/speakers/list.html
Labels: ✅ Approved

#123 fix: event tags multi language
  themes/p2pparis/layouts/partials/s_item.html
Labels: ✅ Approved

#124 Improve permalinks
  themes/p2pparis/layouts/partials/block_speaker.html
  themes/p2pparis/layouts/partials/block_talk.html
  themes/p2pparis/layouts/partials/section_speakers.html
  themes/p2pparis/layouts/speakers/list.html
  themes/p2pparis/layouts/speakers/single.html
  themes/p2pparis/layouts/talks/single.html
Labels: 🔍 Ready for Review

#122 Dev/alex/speakers and talks
  content/event/festival-0/paris_p2p_festival_0_small.png
  content/event/monthly-0/paris_p2p_event_0_small.png
  content/event/monthly-1/paris_p2p_event_monthly_small.png
  content/event/monthly-2/paris_p2p_event_monthly_small.png
  content/event/monthly-3/paris_p2p_event_monthly_small.png
  content/event/monthly-4/paris_p2p_event_monthly_small.png
  content/event/monthly-5/paris_p2p_event_monthly_small.png
  content/event/monthly-6/paris_p2p_event_monthly_small.png
  content/event/monthly-7/paris_p2p_event_monthly_small.png
  content/event/monthly-8/paris_p2p_event_monthly_small.png
  content/event/monthly-9/paris_p2p_event_monthly_small.png
  i18n/en.yaml
  i18n/fr.yaml
  themes/p2pparis/assets/css/creative.css
  themes/p2pparis/layouts/partials/block_speaker.html
  themes/p2pparis/layouts/partials/block_talk.html
  themes/p2pparis/layouts/partials/section_speakers.html
  themes/p2pparis/layouts/speakers/list.html
  themes/p2pparis/layouts/speakers/single.html
  themes/p2pparis/layouts/talks/list.html
  themes/p2pparis/layouts/talks/single.html
  themes/p2pparis/static/js/creative.js
Labels: ✅ Approved

#126 feat: Add festival talk permalinks
  themes/p2pparis/layouts/partials/s_item.html
Labels: ✅ Approved

#125 Festival improvements
  content/event/festival-0/index.fr.md
  content/event/festival-0/index.md
  themes/p2pparis/assets/css/creative.css
  themes/p2pparis/layouts/partials/header.html
  themes/p2pparis/layouts/partials/s_item.html
  themes/p2pparis/layouts/partials/section_info.html
  themes/p2pparis/layouts/partials/section_links.html
Labels: 🔍 Ready for Review

#128 fix: Handle Airtable pagination
  scripts/generate-airtable-pages.js
Labels: ✅ Approved, 🔍 Ready for Review

#129 Dev/alex/update festival plan
  themes/p2pparis/assets/css/creative.css
  themes/p2pparis/static/img/ground_control_floor_plan.svg
Labels: 🔍 Ready for Review

#130 chore: redirect subdomains to main one
  themes/p2pparis/static/_redirects
Labels: ✅ Approved

#131 Filter events on schedule
  content/print/_index.fr.md
  content/print/_index.md
  i18n/en.yaml
  i18n/fr.yaml
  themes/p2pparis/assets/css/creative.css
  themes/p2pparis/layouts/partials/s_filters.html
  themes/p2pparis/layouts/partials/s_item.html
  themes/p2pparis/layouts/partials/section_schedule.html
  themes/p2pparis/layouts/print/list.html
  themes/p2pparis/static/js/creative.js
Labels: ✅ Approved

#132 Dev/alex/modular countdown
  content/event/festival-0/index.fr.md
  content/event/festival-0/index.md
  i18n/en.yaml
  themes/p2pparis/assets/css/creative.css
  themes/p2pparis/layouts/partials/masthead_festival.html
  themes/p2pparis/static/js/creative.js
Labels: ✅ Approved

#133 Fix festival location
  scripts/generate-airtable-pages.js
  themes/p2pparis/layouts/partials/s_item.html
Labels: ✅ Approved

#134 fix: location on talk page
  themes/p2pparis/layouts/partials/block_talk.html
Labels: ✅ Approved

#135 feat: update location data for filters
  themes/p2pparis/layouts/partials/s_item.html
Labels: 🔍 Ready for Review

#136 Dev/alex/video
  i18n/en.yaml
  i18n/fr.yaml
  scripts/generate-airtable-pages.js
  themes/p2pparis/assets/css/creative.css
  themes/p2pparis/layouts/partials/block_talk.html
  themes/p2pparis/layouts/partials/s_item.html
Labels: 🔍 Ready for Review

#138 feat: fix airplane filter
  themes/p2pparis/layouts/partials/s_item.html
Labels: 🔍 Ready for Review

#137 Airtable script fixes
  .gitignore
  package-lock.json
  package.json
  scripts/generate-airtable-pages.js
Labels: ✅ Approved

#139 feat: only display video preview when link is available
  themes/p2pparis/assets/css/creative.css
  themes/p2pparis/layouts/partials/s_item.html
Labels: 🔍 Ready for Review

#140 airtable script improvements
  scripts/generate-airtable-pages.js
  themes/p2pparis/layouts/partials/block_talk.html
Labels: ✅ Approved

#141 feat: add block donate at top of page + improve speaker blocks respon…
  content/event/festival-0/index.fr.md
  content/event/festival-0/index.md
  themes/p2pparis/assets/css/creative.css
  themes/p2pparis/layouts/event/festival.html
  themes/p2pparis/layouts/partials/section_donate.html
  themes/p2pparis/layouts/partials/section_schedule.html
Labels: 🔍 Ready for Review

#143 handle missing slug
  scripts/generate-airtable-pages.js
  themes/p2pparis/layouts/partials/section_speakers.html
  themes/p2pparis/layouts/talks/single.html
Labels: ✅ Approved

#142 feat: add a mobile friendly display mode for events
  i18n/en.yaml
  i18n/fr.yaml
  themes/p2pparis/assets/css/creative.css
  themes/p2pparis/layouts/partials/s_filters.html
  themes/p2pparis/layouts/partials/s_item_light.html
  themes/p2pparis/layouts/partials/section_schedule.html
  themes/p2pparis/layouts/talks/single.html
  themes/p2pparis/static/js/creative.js
Labels: 🔍 Ready for Review

#144 feat: fix for talks that don't have a slug
  themes/p2pparis/layouts/partials/s_item_light.html
Labels: 🔍 Ready for Review

#145 Add ld+json
  config.yml
  content/_index.fr.md
  content/_index.md
  scripts/generate-airtable-pages.js
  themes/p2pparis/assets/img/logo.png
  themes/p2pparis/layouts/partials/header.html
  themes/p2pparis/layouts/partials/ldjson/breadcrumb-inner.html
  themes/p2pparis/layouts/partials/ldjson/breadcrumb.html
  themes/p2pparis/layouts/partials/ldjson/organization-inner.html
  themes/p2pparis/layouts/partials/ldjson/organization.html
  themes/p2pparis/layouts/partials/ldjson/person-inner.html
  themes/p2pparis/layouts/partials/ldjson/person.html
  themes/p2pparis/layouts/partials/ldjson/webpage-inner.html
  themes/p2pparis/layouts/partials/ldjson/webpage.html
  themes/p2pparis/layouts/partials/ldjson/website-inner.html
  themes/p2pparis/layouts/partials/ldjson/website.html
  themes/p2pparis/layouts/partials/section_links.html
  themes/p2pparis/layouts/speakers/single.html
Labels: ✅ Approved

#148 Dev/alex/ark
  themes/p2pparis/assets/css/creative.css
  themes/p2pparis/layouts/partials/block_donator.html
  themes/p2pparis/layouts/partials/section_testimonial.html
  themes/p2pparis/static/img/ark.svg
Labels: 🔍 Ready for Review

#151 Update Airtable base ID
  scripts/generate-airtable-pages.js
Labels: ✅ Approved

#152 add canonical & lang meta tags
  themes/p2pparis/layouts/partials/header.html
Labels: ✅ Approved

#153 Show 2 available slots - talks
  themes/p2pparis/layouts/event/single.html
Labels: ✅ Approved
